### ISSUE TITLE
Pyro Windows 8.1 Issues?

### ISSUE THREAD

**Issue by JerseyJackal** [Gang-Garrison-2/Gang-Garrison-2#153] opened 2015-04-20 22:26 UTC
http://i.imgur.com/J6q4Ytw.png

Looks like it's directmusic's fault in this case. A fluke or could the issues still be unresolved?

**Comment by Medo42** [comment] 2015-04-30 19:59
Unfortunately I can't test this myself because I still run Windows 7, but could you try whether this happens reproducably when two pyros are firing at the same time?

**Comment by arctic5** [comment] 2015-05-02 07:13
id say this is a crash because too many sounds are playing for the sound_stop fix to catch it fast enough

**Comment by wareya** [comment] 2015-05-02 07:19
sound_stop is supposed to stop the sounds at the next internal API step

**Comment by Medo42** [comment] 2015-05-03 22:28
This is just from a quick skim, but we seem to do the sound_stop only for one-shot sounds (playsound script), not for looped sounds (loopsoundstart script). However, calling sound_loop twice on the same sound might be a no-op anyway. I don't have time to test this right now or dig further.

**Comment by Medo42** [comment] 2015-08-16 11:28
The best solution for this would be to finally adopt one of the sound extensions we have available now.

**Comment by Medo42** [comment] 2018-01-19 01:23
Duplicate of #11

**Closed by Medo42** 2018-01-19 01:23 UTC
Labels: OS's fault, crash
