### ISSUE TITLE
Lobby not loading immediately

### ISSUE THREAD

**Issue by hikari-no-yume** [Gang-Garrison-2/Gang-Garrison-2#74] opened 2014-09-01 17:19 UTC
Attempting to display the lobby servers, before the dev message checker has finished results in the screen displaying the 0/-1 amount of servers, until it ends

Launchpad Details: [#LP758191](https://bugs.launchpad.net/bugs/758191) notagenericname - 2011-04-12 00:10:25 +0100

**Comment by PrOF-kk** [comment] 2018-01-25 17:35
Can't reproduce in 2.8.6. The DevMessageChecker is only displayed for about 0.1 seconds

**Comment by Medo42** [comment] 2018-01-28 21:04
No, definitely still there. It sometimes happens just like that, but I can reproduce it by changing my network config to some subnet without connection to the outside world and setting a bogus gateway and DNS server.

**Comment by Medo42** [comment] 2018-01-29 02:01
Soo, what happens is that boost::asio fakes async DNS queries by putting them on a special thread. However, there is only one of these threads, so you only get one DNS query at a time. If the dev message checker needs a bit to resolve ganggarrison.com, no further TCP connection can be opened until that query completes (and it cannot be interrupted either). This even goes for TCP connections that are opened directly to an IP, because those IPs are still pushed through the DNS resolver.

I changed Faucet Net in order to make sure connecting by IP literal does not use the DNS resolver anymore. That strategy was already in the UDP code, but not in the TCP code.

I may also change gg2 in order to do fewer lookups, since we only ever really look up ganggarrison.com and that only needs to be done once. Not sure if it's worth fixing the underlying "serial" nature of the DNS lookups by introducing more threads or similar, since it's not really buggy (connecting may just take a bit longer if a DNS lookup is involved) and doesn't usually affect the game.

**Comment by Medo42** [comment] 2018-01-30 00:35
Oh well, closing this after all. The Faucet Net update fixes my part of the issue where hosting would fail, but would not have an impact on the original issue by NAGN. I don't think it's worth putting more time into this unless someone complains again though, since the basic issue is a bad / slow networking situation causing slow DNS lookups.

**Closed by Medo42** 2018-01-30 00:35 UTC
Labels: annoyance
