### ISSUE TITLE
Server crash, "Unknown variable object." 

### ISSUE THREAD

**Issue by TCrouse** [Gang-Garrison-2/Gang-Garrison-2#142] opened 2015-03-02 00:56 UTC
BTW I am Server consistently crashes due to unknown variable "object" on "global.myself."  I have been unable to actively reproduce this or identify how long into execution this occurs.

I have attached screenshots of two separate occurrences, the first including plugins and the second without any plugins.  The error is the same but the steps and objects at which they occurred are different.

Instance with plugins:
![pluginsenabled](https://cloud.githubusercontent.com/assets/2835885/6434004/5766f108-c04c-11e4-9372-046d8f417472.png)

Instance without plugins:
![noplugins](https://cloud.githubusercontent.com/assets/2835885/6434006/5aaf3870-c04c-11e4-9793-e1878dd719c6.png)

**Comment by wareya** [comment] 2015-03-02 00:58
global.myself is getting a bad value somehow. Especially as a server it should be essentially impossible for it to not point at the server's player. The only reasons I can think of are something like a plugin modifying it badly, bad RAM, a broken copy of GG2, or an obscure bug. grep myself -r src/gg2 anyone?

**Comment by TCrouse** [comment] 2015-03-02 01:09
This does occur when no plugins are included.  The RAM was installed a month ago and has tested fine. I will try downloading a new copy of GG2 and run it without any plugins first, and report back.

**Comment by arctic5** [comment] 2015-03-02 08:07
so i asked nagn

**Comment by arctic5** [comment] 2015-03-02 08:08
so i asked nagn since he seems like he might be knowledgeable on the subject

9:07 PM - NAGN: not sure
9:07 PM - NAGN: this bug or variants of it have been floating around for years now
9:08 PM - NAGN: it may have something to do with the memory being corrupted by the game maker interpretter itself
9:08 PM - NAGN: but we really have no evidence and its pretty difficult to reproduce the error

9:12 PM - NAGN: its not a hardware issue

9:14 PM - NAGN: is there any way to dump the game state when the game crashes
9:14 PM - arctismo: i dont think so
9:14 PM - arctismo: is there a way to even get the game state
9:29 PM - NAGN: the best I can thinkof is some sort of conditional that checks what global.myself is defined as
9:29 PM - NAGN: if it ever is not a Player object, then pause and figure out what part of the code it is occuring in

**Comment by Medo42** [comment] 2015-03-09 01:06
I looked at this for a while today and didn't find any obvious mechanism that could cause this error either. Maybe we should create a debug build which has added checks in GameServerBeginStep (where the removePlayer script is called), as well as Player Destroy, plus the places in the code where the errors popped up. This might allow us to narrow down what actually happens.

@TCrouse Can you confirm that you disabled all plugins, including server-sent plugins in the ini?

**Comment by TCrouse** [comment] 2015-03-09 05:50
I did disable all plugins and server-sent plugins at one point, including deleting several directories created by server-sent plugins.  As of 1:45 AM EST I am hosting a fresh copy of the game, having changed only the following settings:

PlayerName=BTW I am Server
HostingPort=8192
Music=0
PlayerLimit=18
Particles=1
Gib Level=0
Kill Cam=0
Healer Radar=0
Show Healer=0
Show Healing=0
Dedicated=1
ServerName=[USA] BTW I am Server
CapLimit=3
Respawn Time=7
Time Limit=10

**Comment by TCrouse** [comment] 2015-03-09 23:21
The vanilla instance of GG2 has crashed with the following error:

___________________________________________
ERROR in
action number 1
of Begin Step Event
for object AmmoCounter:

Error in code at line 1:
   if global.myself.object == -1 instance_destroy();
                   ^
at position 18: Unknown variable object

**Comment by arctic5** [comment] 2015-03-11 23:12
6:57 PM - BTW I am Infiltrator: Might be manifesting itself in the first map though
6:57 PM - BTW I am Infiltrator: I can join when server first starts
6:56 PM - arctismo: :O yea maybe one of ur maps suck
6:57 PM - BTW I am Infiltrator: fack you
6:57 PM - BTW I am Infiltrator: Then at some point I lose control of my character
6:56 PM - arctismo: wuuuuut the
6:57 PM - BTW I am Infiltrator: Cant update the player info either
6:56 PM - arctismo: hm
6:56 PM - arctismo: maybe ur player object is lik
6:56 PM - arctismo: radioactive
6:56 PM - arctismo: and it slowly decays
6:58 PM - BTW I am Infiltrator: Couldnt even switch from team to spectate
6:57 PM - arctismo: so at that point ur team variable probably decayed

**Comment by Medo42** [comment] 2015-03-11 23:58
A more complete description of what happened would be useful. In parcicular
- Did this happen when playing directly on the server, or connected as client?
- when in the course of play did this happen? (e.g. just after map change, middle of a match, when respawning)
- What is meant by "lose control of my character"? Did the character cease to move at all, or run around as if controlled by someone else?
- Could you establish that the camera was actually still following your character, or did it perhaps switch to follow someone else? The only way you could really tell is if it happened mid-play, if you lost control without the camera changing.
To be honest though, if no other server host is reporting this problem, then perhaps we should check over the hardware, since the mechanism of failure seems so elusive. Could you run Prime95 to stress-test both CPU and RAM for a few hours?

**Comment by TCrouse** [comment] 2015-03-17 22:23
So, I've switched to hosting from another machine and have yet to experience the same issue.

I stress-tested with Prime95 not even a month before, which tested fine after 12 hours.  Last night, Prime95 crashed my machine somewhere under 10 hours.

I am willing to write this off as a user/hardware error unless anybody wants to pursue further.  Thanks a ton for your help.

**Comment by arctic5** [comment] 2015-03-19 05:38
so I guess we can close this now?

**Closed by arctic5** 2015-03-19 05:38 UTC
Labels: Hardware

**Comment by Medo42** [comment] 2015-03-19 10:43
For now, yes.

If the problem comes up again on the new machine though, we have
confirmation that it's not a hardware issue and can reopen this.

jason <notifications@github.com> schrieb am Do., 19.03.2015, 6:38:
