### ISSUE TITLE
Auto Balance defies class limits

### ISSUE THREAD

**Issue by TheRocketJumper** [Gang-Garrison-2/Gang-Garrison-2#165] opened 2015-11-07 10:43 UTC
I was auto balanced to the enemy team with a class limit of 2 scouts, but when I spawned I saw that the numbers of the scout class limit was: 3/2

I have a screenie but I am not using my laptop.

**Comment by arctic5** [comment] 2015-11-07 11:48
duplicate of https://github.com/Gang-Garrison-2/Gang-Garrison-2/issues/9

**Comment by arctic5** [comment] 2015-11-07 11:49
crap wrong bug report

**Closed** 2015-12-31 13:30 UTC
Labels: bug
